# Generated by Django 4.1.4 on 2023-01-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mauli', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=30)),
                ('quantity', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
                ('fullname', models.CharField(max_length=30)),
                ('phoneno', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=30)),
            ],
        ),
    ]
